azs:
- name: z1
  cloud_properties:
    availability_zone: ((az))

vm_types:
- name: default
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000}

disk_types:
- name: default
  disk_size: 3000
  cloud_properties: {}

networks:
- name: default
  type: manual
  subnets:
  - range:    ((internal_cidr))
    gateway:  ((internal_gw))
    az:       z1
    dns:      [8.8.8.8]
    static:   [((static_range))]
    reserved:   [((reserved_range))]
    cloud_properties:
      subnet: ((subnet_id))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
