---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-cpi-src
  - name: bosh-cli
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: environment
  - name: certification
  - name: bosh-deployment

outputs:
  - name: director-config

run:
  path: bosh-cpi-src/ci/tasks/prepare-director.sh

params:
  AWS_ACCESS_KEY:              ""
  AWS_SECRET_KEY:              ""
  AWS_REGION_NAME:             ""
  BOSH_CLIENT_SECRET:          ""
  ENABLE_IAM_INSTANCE_PROFILE: ""
  PUBLIC_KEY_NAME:             ""
  PRIVATE_KEY_DATA:            ""
