---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: release-version-semver
run:
  path: bosh-cpi-src/ci/tasks/promote-candidate.sh
params:
  aws_access_key_id:     replace-me
  aws_secret_access_key: replace-me
