---
platform: linux
image: docker:///bosh/aws-cpi-release
inputs:
- name: bats
- name: stemcell
- name: bosh-concourse-ci
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  BAT_VCAP_PASSWORD:    replace-me
  BAT_STEMCELL:         replace-me
  BAT_DEPLOYMENT_SPEC:  replace-me
  BAT_VCAP_PRIVATE_KEY: replace-me
  base_os:              replace-me
