---
platform: linux
image: docker:///bosh/aws-cpi-release
inputs:
- name: bosh-cpi-dev-artifacts
- name: stemcell
- name: bosh-cpi-release
- name: terraform-exports
- name: bosh-concourse-ci
- name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  base_os:              replace-me
  BAT_VCAP_PASSWORD:    replace-me
  BAT_VCAP_PRIVATE_KEY: replace-me
