---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: environment
run:
  path: bosh-cpi-src/ci/tasks/run-integration.sh
params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION:    ""
  AWS_PUBLIC_KEY_NAME:   ""
