---
platform: linux
image: docker:///bosh/aws-cpi-release
inputs:
- name: deploy            # --- task that updated the deployment state
- name: bosh-cpi-release  # --- makes available the sh script below
run:
  path: bosh-cpi-release/ci/tasks/save-deployment.sh
params:
  base_os: replace-me
