---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: bosh-cpi-src
  - name: bosh-init
  - name: bosh-release
  - name: stemcell
outputs:
  - name: deployment
run:
  path: bosh-cpi-src/ci/tasks/setup-director.sh
params:
  stack_prefix:          replace-me
  stack_name:            replace-me
  aws_access_key_id:     replace-me
  aws_secret_access_key: replace-me
  private_key_data:      replace-me
  public_key_name:       replace-me
  region_name:           replace-me
  director_username:     replace-me
  director_password:     replace-me
  use_iam:               replace-me
  blobstore_s3_region:
  BOSH_INIT_LOG_LEVEL:   warn
