---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
- name: bosh-cpi-src
- name: bosh-init
- name: deployment
run:
  path: bosh-cpi-src/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL:        warn
