---
ruby_aws_cpi/ruby-1.9.3-p545.tar.gz:
  object_id: 67b78097-09b0-4ee4-858f-10b12581a613
  sha: !binary |-
    MDM0NTUzNjQ3NDA5MTRlOGQyZGZkNjQyMWY2ODFiM2ZiNjhhNDMxMw==
  size: 12582277
ruby_aws_cpi/rubygems-2.1.11.tgz:
  object_id: 37aaa35c-5464-408f-a3b0-2cd23f6193fc
  sha: !binary |-
    Y2EzMDMzNDMyY2FlMjhkZWI3Y2VkNzljZGEyNzFjYjI5MmI3MGU1OQ==
  size: 367166
ruby_aws_cpi/yaml-0.1.5.tar.gz:
  object_id: 0907b454-e880-4943-97a1-a6c1698d91f9
  sha: !binary |-
    OGI3OGNiOWY3NTljN2Q4MGRiOGE3MzI4YzBlYmVjZmUzNGZkZTczNw==
  size: 504897
