---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - bosh-integration
      - promote-candidate

  - name: primary
    jobs:
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - promote-candidate

  - name: bosh-integration
    jobs:
      - build-candidate
      - bosh-integration
      - promote-candidate

  - name: china
    jobs:
      - setup-downloader-infrastructure-cn
      - download-from-cn
      - teardown-downloader-infrastructure-cn

  - name: all
    jobs:
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - bosh-integration
      - promote-candidate
      - recreate-infrastructure-primary
      - recreate-infrastructure-bosh-integration
      - setup-downloader-infrastructure-cn
      - download-from-cn
      - teardown-downloader-infrastructure-cn

jobs:
  - name: recreate-infrastructure-primary
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: check-for-running-instances
        file: bosh-cpi-release/ci/tasks/check-for-running-instances.yml
        config: &recreate-primary-config
          params:
            aws_access_key_id:        {{aws_access_key__primary}}
            aws_secret_access_key:    {{aws_secret_key__primary}}
            region_name:              {{aws_region__primary}}
            stack_name:               primary

      - task: cloudformation
        file: bosh-cpi-release/ci/tasks/cloudformation.yml
        config: *recreate-primary-config

  - name: recreate-infrastructure-bosh-integration
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: check-for-running-instances
        file: bosh-cpi-release/ci/tasks/check-for-running-instances.yml
        config: &recreate-bosh-integration-config
          params:
            aws_access_key_id:        {{aws_access_key__bosh_integration}}
            aws_secret_access_key:    {{aws_secret_key__bosh_integration}}
            region_name:              {{aws_region__bosh_integration}}
            stack_name:               bosh-integration

      - task: cloudformation
        file: bosh-cpi-release/ci/tasks/cloudformation.yml
        config: *recreate-bosh-integration-config

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: build/out/.*\.tgz}

  - name: lifecycle
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-release-in}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        config:
          params:
            aws_access_key_id:            {{aws_access_key__primary}}
            aws_secret_access_key:        {{aws_secret_key__primary}}
            region_name:                  {{aws_region__primary}}
            stack_name:                   primary

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    Ubuntu
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    Ubuntu
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_ubuntu}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-centos-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    Centos
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    Centos
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_centos}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: bosh-integration
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false,                            get: stemcell, resource: {{bosh-integration-stemcell-resource-name}} }
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                            get: bosh-init}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false,                            get: bosh-release}
        - {trigger: false,                            get: dummy-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director-iam.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__bosh_integration}}
            aws_secret_access_key: {{aws_secret_key__bosh_integration}}
            region_name:           {{aws_region__bosh_integration}}
            private_key_data:      {{bosh_private_key}}
            stack_name:            bosh-integration
            blobstore_s3_host:     {{blobstore_s3_host__bosh_integration}}

      - task: test
        file: bosh-cpi-release/ci/tasks/iam-test.yml
        config:
          params:
            aws_access_key_id:          {{aws_access_key__bosh_integration}}
            aws_secret_access_key:      {{aws_secret_key__bosh_integration}}
            region_name:                {{aws_region__bosh_integration}}
            stemcell_name:              {{BAT_STEMCELL_NAME_ubuntu}}
            stack_name:                 bosh-integration

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: promote-candidate
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-dev-artifacts, passed: [lifecycle, bats-ubuntu, bats-centos, bosh-integration]}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-out}
        - {trigger: false, get: release-version-semver, params: {bump: major}}

      - task: promote
        file: bosh-cpi-release/ci/tasks/promote-candidate.yml
        config:
          params:
            aws_access_key_id: {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}

      - put: bosh-cpi-release
        resource: bosh-cpi-release-out
        params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

      - put: release-version-semver
        params: {file: release-version-semver/number}

  - name: setup-downloader-infrastructure-cn
    serial_groups: [download-cn]
    plan:
      - aggregate:
        - {trigger: true, get: one-hour-timer}
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: cloudformation
        file: bosh-cpi-release/ci/tasks/cloudformation.yml
        config: &downloader-infrastructure-config
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn

  - name: download-from-cn
    serial_groups: [download-cn]
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-release, passed: [setup-downloader-infrastructure-cn], resource: bosh-cpi-release-in}

      - task: download
        file: bosh-cpi-release/ci/tasks/download-bits.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn
            private_key_data:      {{bosh_private_key}}
        on_failure:
          task: teardown
          file: bosh-cpi-release/ci/tasks/teardown-infrastructure.yml
          config: *downloader-infrastructure-config


  - name: teardown-downloader-infrastructure-cn
    serial_groups: [download-cn]
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-release, passed: [download-from-cn], resource: bosh-cpi-release-in}

      - task: teardown
        file: bosh-cpi-release/ci/tasks/teardown-infrastructure.yml
        config: *downloader-infrastructure-config

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-release-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-release-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{s3_bosh_init_bucket}}
      region_name: {{aws_region__primary}}

  - name: dummy-release
    type: s3
    source:
      versioned_file: dummy.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: aws-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: aws-bosh-integration-stemcell
    type: s3
    source:
      versioned_file: stemcell.tgz
      bucket: {{s3_aws_cpi_bosh_integration_stemcell_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: aws-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-centos-7-go_agent

  - name: one-hour-timer
    type: time
    source:
      interval: 1h
