---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - promote-candidate

  - name: primary
    jobs:
      - recreate-infrastructure-primary
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - promote-candidate

  - name: china
    jobs:
      - recreate-infrastructure-cn-downloader
      - download-from-cn

  - name: all
    jobs:
      - recreate-infrastructure-primary
      - recreate-infrastructure-cn-downloader
      - build-candidate
      - bats-ubuntu
      - bats-centos
      - ubuntu-pv-radiator
      - centos-pv-radiator
      - lifecycle
      - promote-candidate
      - download-from-cn

jobs:
  - name: recreate-infrastructure-primary
    serial_groups: [primary-centos, primary-ubuntu]
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: check-for-running-instances
        file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
        config: &recreate-primary-config
          params:
            aws_access_key_id:        {{aws_access_key__primary}}
            aws_secret_access_key:    {{aws_secret_key__primary}}
            region_name:              {{aws_region__primary}}
            stack_name:               primary
            stack_prefix:             not-applicable

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        config: *recreate-primary-config

      - task: setup-infrastructure
        file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
        config: *recreate-primary-config

  - name: recreate-infrastructure-cn-downloader
    serial_groups: [china]
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        config: &recreate-downloader-config
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn
            stack_prefix:          not-applicable

      - task: setup-infrastructure
        file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
        config: *recreate-downloader-config

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-src/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: candidate/.*\.tgz}

  - name: lifecycle
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        config:
          params:
            aws_access_key_id:            {{aws_access_key__primary}}
            aws_secret_access_key:        {{aws_secret_key__primary}}
            region_name:                  {{aws_region__primary}}
            stack_name:                   primary

  - name: bats-ubuntu
    serial_groups: [primary-ubuntu]
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-hvm-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            stack_prefix:          Ubuntu
            stack_name:            primary
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            private_key_data:      {{bosh_private_key}}
            public_key_name:       {{bosh_public_key_name}}
            director_username:     {{bosh_director_username}}
            director_password:     {{bosh_director_password}}

      - task: run-bats
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        config:
          params:
            base_os:               Ubuntu
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            BAT_VCAP_PASSWORD:     {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:     {{BAT_STEMCELL_NAME_hvm_ubuntu}}
            public_key_name:       {{bosh_public_key_name}}
            stack_name:            primary

      - task: teardown-director
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: bats-centos
    serial_groups: [primary-centos]
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-centos-hvm-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            stack_prefix:          Centos
            stack_name:            primary
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            private_key_data:      {{bosh_private_key}}
            public_key_name:       {{bosh_public_key_name}}
            director_username:     {{bosh_director_username}}
            director_password:     {{bosh_director_password}}

      - task: run-bats
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        config:
          params:
            base_os:               Centos
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            BAT_VCAP_PASSWORD:     {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:     {{BAT_STEMCELL_NAME_hvm_centos}}
            public_key_name:       {{bosh_public_key_name}}
            stack_name:            primary

      - task: teardown-director
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: ubuntu-pv-radiator
    serial_groups: [primary-ubuntu]
    plan:
      - aggregate:
        - {trigger: true,  get: three-hour-timer}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: stemcell, resource: aws-ubuntu-stemcell}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            stack_prefix:          UbuntuPV
            stack_name:            primary
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            private_key_data:      {{radiator_private_key}}
            public_key_name:       {{radiator_public_key_name}}
            director_username:     {{bosh_director_username}}
            director_password:     {{bosh_director_password}}
        on_failure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - task: deploy-dummy
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            base_os:                    UbuntuPV
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            stemcell_name:              {{BAT_STEMCELL_NAME_ubuntu}}
            stack_name:                 primary
            director_username:          {{bosh_director_username}}
            director_password:          {{bosh_director_password}}
        ensure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: centos-pv-radiator
    serial_groups: [primary-centos]
    plan:
      - aggregate:
        - {trigger: true,  get: three-hour-timer}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: stemcell, resource: aws-centos-stemcell}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            stack_prefix:          CentosPV
            stack_name:            primary
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            region_name:           {{aws_region__primary}}
            private_key_data:      {{radiator_private_key}}
            public_key_name:       {{radiator_public_key_name}}
            director_username:     {{bosh_director_username}}
            director_password:     {{bosh_director_password}}
        on_failure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

      - task: deploy-dummy
        file: bosh-cpi-src/ci/tasks/deploy-dummy.yml
        config:
          params:
            base_os:                    CentosPV
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            stemcell_name:              {{BAT_STEMCELL_NAME_centos}}
            stack_name:                 primary
            director_username:          {{bosh_director_username}}
            director_password:          {{bosh_director_password}}
        ensure:
          task: teardown-director
          file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: promote-candidate
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts, passed: [lifecycle, bats-ubuntu, bats-centos]}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-out}
        - {trigger: false, get: release-version-semver, params: {bump: major}}

      - task: promote
        file: bosh-cpi-src/ci/tasks/promote-candidate.yml
        config:
          params:
            aws_access_key_id: {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}

      - put: bosh-cpi-src-out
        params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

      - put: release-version-semver
        params: {file: release-version-semver/number}

  - name: download-from-cn
    serial_groups: [china]
    plan:
      - aggregate:
        - {trigger: true,  get: one-hour-timer}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: download
        file: bosh-cpi-src/ci/tasks/download-bits.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn
            private_key_data:      {{bosh_private_key}}

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{s3_bosh_init_bucket}}
      region_name: {{aws_region__primary}}

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-aws-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: aws-ubuntu-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: aws-centos-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-centos-7-go_agent

  - name: aws-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-ubuntu-trusty-go_agent

  - name: aws-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-centos-7-go_agent

  - name: one-hour-timer
    type: time
    source:
      interval: 1h

  - name: three-hour-timer
    type: time
    source:
      interval: 3h
