---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - build-candidate
      - bats-hvm-ubuntu
      - bats-hvm-centos
      - lifecycle
      - end2end-primary
      - promote-candidate

  - name: primary
    jobs:
      - recreate-infrastructure-primary
      - recreate-infrastructure-end2end-primary
      - build-candidate
      - bats-hvm-ubuntu
      - bats-hvm-centos
      - lifecycle
      - end2end-primary
      - promote-candidate

  - name: end2end
    jobs:
      - recreate-infrastructure-end2end-primary
      - build-candidate
      - end2end-primary
      - promote-candidate

  - name: china
    jobs:
      - recreate-infrastructure-cn-downloader
      - download-from-cn

  - name: all
    jobs:
      - recreate-infrastructure-primary
      - recreate-infrastructure-end2end-primary
      - recreate-infrastructure-cn-downloader
      - build-candidate
      - bats-hvm-ubuntu
      - bats-hvm-centos
      - bats-ubuntu
      - bats-centos
      - lifecycle
      - end2end-primary
      - promote-candidate
      - download-from-cn

jobs:
  - name: recreate-infrastructure-primary
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: check-for-running-instances
        file: bosh-cpi-release/ci/tasks/check-for-running-instances.yml
        config: &recreate-primary-config
          params:
            aws_access_key_id:        {{aws_access_key__primary}}
            aws_secret_access_key:    {{aws_secret_key__primary}}
            region_name:              {{aws_region__primary}}
            stack_name:               primary

      - task: teardown-infrastructure
        file: bosh-cpi-release/ci/tasks/teardown-infrastructure.yml
        config: *recreate-primary-config

      - task: setup-infrastructure
        file: bosh-cpi-release/ci/tasks/setup-infrastructure.yml
        config: *recreate-primary-config

  - name: recreate-infrastructure-end2end-primary
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: check-for-running-instances
        file: bosh-cpi-release/ci/tasks/check-for-running-instances.yml
        config: &recreate-end2end-primary-config
          params:
            aws_access_key_id:        {{aws_access_key__e2e_primary}}
            aws_secret_access_key:    {{aws_secret_key__e2e_primary}}
            region_name:              {{aws_region__e2e_primary}}
            stack_name:               end2end

      - task: teardown-infrastructure
        file: bosh-cpi-release/ci/tasks/teardown-infrastructure.yml
        config: *recreate-end2end-primary-config

      - task: setup-infrastructure
        file: bosh-cpi-release/ci/tasks/setup-infrastructure.yml
        config: *recreate-end2end-primary-config

  - name: recreate-infrastructure-cn-downloader
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

      - task: teardown-infrastructure
        file: bosh-cpi-release/ci/tasks/teardown-infrastructure.yml
        config: &recreate-downloader-config
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn

      - task: setup-infrastructure
        file: bosh-cpi-release/ci/tasks/setup-infrastructure.yml
        config: *recreate-downloader-config

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: build/out/.*\.tgz}

  - name: lifecycle
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-release-in}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
        config:
          params:
            aws_access_key_id:            {{aws_access_key__primary}}
            aws_secret_access_key:        {{aws_secret_key__primary}}
            region_name:                  {{aws_region__primary}}
            stack_name:                   primary

  - name: bats-hvm-ubuntu
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-hvm-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    UbuntuHVM
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    UbuntuHVM
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_hvm_ubuntu}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: bats-hvm-centos
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-centos-hvm-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    CentosHVM
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    Centos
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_hvm_centos}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    Ubuntu
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    Ubuntu
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_ubuntu}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-centos-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director.yml
        config:
          params:
            base_os:                    Centos
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

      - task: run-bats
        file: bosh-cpi-release/ci/tasks/run-bats.yml
        config:
          params:
            base_os:                    Centos
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_centos}}
            stack_name:                 primary

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: end2end-primary
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
        - {trigger: false,                            get: stemcell, resource: aws-ubuntu-hvm-stemcell }
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                            get: bosh-init}
        - {trigger: false, passed: [build-candidate], get: version-semver}
        - {trigger: false,                            get: bosh-release}

      - task: setup-director
        file: bosh-cpi-release/ci/tasks/setup-director-iam.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__e2e_primary}}
            aws_secret_access_key: {{aws_secret_key__e2e_primary}}
            region_name:           {{aws_region__e2e_primary}}
            private_key_data:      {{e2e_private_key}}
            stack_name:            end2end
            blobstore_s3_host:     {{blobstore_s3_host__e2e_primary}}
            director_username:     {{bosh_director_username}}
            director_password:     {{bosh_director_password}}

      - task: test
        file: bosh-cpi-release/ci/tasks/run-e2e.yml
        config:
          params:
            aws_access_key_id:          {{aws_access_key__e2e_primary}}
            aws_secret_access_key:      {{aws_secret_key__e2e_primary}}
            region_name:                {{aws_region__e2e_primary}}
            stemcell_name:              {{BAT_STEMCELL_NAME_hvm_ubuntu}}
            stack_name:                 end2end
            director_username:          {{bosh_director_username}}
            director_password:          {{bosh_director_password}}

      - task: teardown-director
        file: bosh-cpi-release/ci/tasks/teardown-director.yml

  - name: promote-candidate
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-dev-artifacts, passed: [lifecycle, bats-hvm-ubuntu, bats-hvm-centos, end2end-primary]}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-out}
        - {trigger: false, get: release-version-semver, params: {bump: major}}

      - task: promote
        file: bosh-cpi-release/ci/tasks/promote-candidate.yml
        config:
          params:
            aws_access_key_id: {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}

      - put: bosh-cpi-release
        resource: bosh-cpi-release-out
        params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

      - put: release-version-semver
        params: {file: release-version-semver/number}

  - name: download-from-cn
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  get: one-hour-timer}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}

      - task: download
        file: bosh-cpi-release/ci/tasks/download-bits.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__downloader}}
            aws_secret_access_key: {{aws_secret_key__downloader}}
            region_name:           {{aws_region__downloader}}
            stack_name:            downloader-cn
            private_key_data:      {{bosh_private_key}}

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-release-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-release-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{s3_bosh_init_bucket}}
      region_name: {{aws_region__primary}}

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: aws-ubuntu-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: aws-centos-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-centos-7-go_agent

  - name: aws-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-ubuntu-trusty-go_agent

  - name: aws-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-centos-7-go_agent

  - name: one-hour-timer
    type: time
    source:
      interval: 1h
