---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - build-candidate
      - recreate-infrastructure
      - deploy-ubuntu
      - bats-ubuntu
      - deploy-centos
      - bats-centos
      - lifecycle
      - promote-candidate

  - name: ubuntu
    jobs:
      - build-candidate
      - deploy-ubuntu
      - bats-ubuntu
      - promote-candidate

  - name: centos
    jobs:
      - build-candidate
      - deploy-centos
      - bats-centos
      - promote-candidate

jobs:
- name: build-candidate
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false, get: version-semver, params: {bump: patch}}

  - put: version-semver
    params: {file: version-semver/number}

  - task: build
    file: bosh-cpi-release/ci/tasks/build-candidate.yml

  - put: bosh-cpi-dev-artifacts
    params: {from: build/out/.*\.tgz}

- name: lifecycle
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-release-in}

  - task: test
    file: bosh-cpi-release/ci/tasks/run-lifecycle.yml
    config:
      params:
        aws_access_key_id:            {{s3_aws_cpi_access_key}}
        aws_secret_access_key:        {{s3_aws_cpi_secret_key}}
        region_name:                  {{s3_aws_cpi_region}}
        lifecycle_manual_ip:          {{lifecycle_BOSH_AWS_LIFECYCLE_MANUAL_IP}}

- name: recreate-infrastructure
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-release,     resource: bosh-cpi-release-in}

  - task: cloudformation
    file: bosh-cpi-release/ci/tasks/cloudformation.yml
    config:
      params:
        aws_access_key_id:        {{s3_aws_cpi_access_key}}
        aws_secret_access_key:    {{s3_aws_cpi_secret_key}}
        region_name:              us-east-1

- name: deploy-ubuntu
  serial_groups: [ubuntu]
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate],  get: version-semver}
    - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false,                             get: director-state-file, resource: ubuntu-director-state-file}
    - {trigger: false,                             get: bosh-init}
    - {trigger: false,                             get: bosh-release}
    - {trigger: false,                             get: stemcell, resource: aws-ubuntu-stemcell}

  - task: deploy
    file: bosh-cpi-release/ci/tasks/deploy.yml
    config:
      params:
        base_os:                    ubuntu
        aws_access_key_id:          {{s3_aws_cpi_access_key}}
        aws_secret_access_key:      {{s3_aws_cpi_secret_key}}
        region_name:                {{s3_aws_cpi_region}}
        private_key_data:           {{bosh_private_key}}
        AWS_NETWORK_CIDR:           {{AWS_NETWORK_CIDR_ubuntu}}
        AWS_NETWORK_GATEWAY:        {{AWS_NETWORK_GATEWAY_ubuntu}}
        PRIVATE_DIRECTOR_STATIC_IP: {{PRIVATE_DIRECTOR_STATIC_IP_ubuntu}}
    ensure:
      do:
      - put: ubuntu-director-state-file
        params: {from: deploy/director-state-file/ubuntu-director-manifest-state.json}
      - put: ubuntu-director-manifest-file
        params: {from: director-state-file/ubuntu-director-manifest.yml}

- name: bats-ubuntu
  serial_groups: [ubuntu]
  plan:
  - aggregate:
    - {trigger: true,  passed: [deploy-ubuntu],    get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [deploy-ubuntu],    get: stemcell, resource: aws-ubuntu-stemcell}
    - {trigger: false, passed: [deploy-ubuntu],    get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false,                             get: bats}
    - {trigger: false,                             get: bosh-init}
    - {trigger: false,                             get: director-state-file, resource: ubuntu-director-state-file}
    - {trigger: false,                             get: director-manifest-file, resource: ubuntu-director-manifest-file}
    - {trigger: false, passed: [build-candidate],  get: version-semver}
    - {trigger: false,                             get: bosh-release}

  - task: test
    file: bosh-cpi-release/ci/tasks/run-bats.yml
    config:
      params:
        base_os:                    ubuntu
        aws_access_key_id:          {{s3_aws_cpi_access_key}}
        aws_secret_access_key:      {{s3_aws_cpi_secret_key}}
        region_name:                {{s3_aws_cpi_region}}
        BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
        private_key_data:           {{bosh_private_key}}
        BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_ubuntu}}
        BAT_SECOND_STATIC_IP:       {{BAT_SECOND_STATIC_IP_ubuntu}}
        BAT_NETWORK_STATIC_IP:      {{BAT_NETWORK_STATIC_IP_ubuntu}}
        BAT_NETWORK_CIDR:           {{AWS_NETWORK_CIDR_ubuntu}}
        BAT_NETWORK_RESERVED_RANGE: {{BAT_NETWORK_RESERVED_RANGE_ubuntu}}
        BAT_NETWORK_GATEWAY:        {{AWS_NETWORK_GATEWAY_ubuntu}}
        BAT_NETWORK_STATIC_RANGE:   {{BAT_NETWORK_STATIC_RANGE_ubuntu}}
    on_success:
      task: teardown-director
      file: bosh-cpi-release/ci/tasks/teardown-director.yml
      config:
        params:
          base_os:                  ubuntu
      ensure:
        do:
        - put: ubuntu-director-state-file
          params: {from: test/director-state-file/ubuntu-director-manifest-state.json}

- name: deploy-centos
  serial_groups: [centos] # shouldn't deploy while bats run
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate],  get: version-semver}
    - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false,                             get: director-state-file, resource: centos-director-state-file}
    - {trigger: false,                             get: bosh-init}
    - {trigger: false,                             get: bosh-release}
    - {trigger: false,                             get: stemcell, resource: aws-centos-stemcell}

  - task: deploy
    file: bosh-cpi-release/ci/tasks/deploy.yml
    config:
      params:
        base_os:                    centos
        aws_access_key_id:          {{s3_aws_cpi_access_key}}
        aws_secret_access_key:      {{s3_aws_cpi_secret_key}}
        region_name:                {{s3_aws_cpi_region}}
        private_key_data:           {{bosh_private_key}}
        AWS_NETWORK_CIDR:           {{AWS_NETWORK_CIDR_centos}}
        AWS_NETWORK_GATEWAY:        {{AWS_NETWORK_GATEWAY_centos}}
        PRIVATE_DIRECTOR_STATIC_IP: {{PRIVATE_DIRECTOR_STATIC_IP_centos}}
    ensure:
      do:
      - put: centos-director-state-file
        params: {from: deploy/director-state-file/centos-director-manifest-state.json}
      - put: centos-director-manifest-file
        params: {from: deploy/director-state-file/centos-director-manifest.yml}

- name: bats-centos
  serial_groups: [centos] # can't run while deploying
  plan:
  - aggregate:
    - {trigger: true,  passed: [deploy-centos],    get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [deploy-centos],    get: stemcell, resource: aws-centos-stemcell}
    - {trigger: false, passed: [deploy-centos],    get: bosh-cpi-release, resource: bosh-cpi-release-in}
    - {trigger: false,                             get: bosh-init}
    - {trigger: false,                             get: director-state-file, resource: centos-director-state-file}
    - {trigger: false,                             get: director-manifest-file, resource: centos-director-manifest-file}
    - {trigger: false, passed: [build-candidate],  get: version-semver}
    - {trigger: false,                             get: bats}
    - {trigger: false,                             get: bosh-release}

  - task: test
    file: bosh-cpi-release/ci/tasks/run-bats.yml
    config:
      params:
        base_os:                    centos
        aws_access_key_id:          {{s3_aws_cpi_access_key}}
        aws_secret_access_key:      {{s3_aws_cpi_secret_key}}
        region_name:                {{s3_aws_cpi_region}}
        BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
        private_key_data:           {{bosh_private_key}}
        BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_centos}}
        BAT_SECOND_STATIC_IP:       {{BAT_SECOND_STATIC_IP_centos}}
        BAT_NETWORK_STATIC_IP:      {{BAT_NETWORK_STATIC_IP_centos}}
        BAT_NETWORK_CIDR:           {{AWS_NETWORK_CIDR_centos}}
        BAT_NETWORK_RESERVED_RANGE: {{BAT_NETWORK_RESERVED_RANGE_centos}}
        BAT_NETWORK_GATEWAY:        {{AWS_NETWORK_GATEWAY_centos}}
        BAT_NETWORK_STATIC_RANGE:   {{BAT_NETWORK_STATIC_RANGE_centos}}
    on_success:
      task: teardown-director
      file: bosh-cpi-release/ci/tasks/teardown-director.yml
      config:
        params:
          base_os:                  centos
      ensure:
        do:
        - put: centos-director-state-file
          params: {from: test/director-state-file/centos-director-manifest-state.json}

- name: promote-candidate
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-dev-artifacts, passed: [lifecycle, bats-ubuntu, bats-centos]}
    - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-out}
    - {trigger: false, get: release-version-semver, params: {bump: major}}

  - task: promote
    file: bosh-cpi-release/ci/tasks/promote-candidate.yml
    config:
      params:
        aws_access_key_id: {{s3_aws_cpi_access_key}}
        aws_secret_access_key: {{s3_aws_cpi_secret_key}}

  - put: bosh-cpi-release
    resource: bosh-cpi-release-out
    params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

  - put: release-version-semver
    params: {file: release-version-semver/number}

resources:
- name: bosh-cpi-dev-artifacts
  type: s3
  source:
    regexp: bosh-aws-cpi\.tgz
    bucket: {{s3_aws_cpi_pipeline_bucket}}
    region_name: {{s3_aws_cpi_region}}
    access_key_id: {{s3_aws_cpi_access_key}}
    secret_access_key: {{s3_aws_cpi_secret_key}}

- name: ubuntu-director-state-file
  type: s3
  source:
    bucket:            {{s3_aws_cpi_ubuntu_director_state_file_bucket}}
    versioned_file:    ubuntu-director-manifest-state.json
    region_name:       us-east-1
    access_key_id:     {{s3_aws_cpi_ubuntu_director_state_file_access_key}}
    secret_access_key: {{s3_aws_cpi_ubuntu_director_state_file_secret_key}}

- name: centos-director-state-file
  type: s3
  source:
    bucket:            {{s3_aws_cpi_centos_director_state_file_bucket}}
    versioned_file:    centos-director-manifest-state.json
    region_name:       us-east-1
    access_key_id:     {{s3_aws_cpi_centos_director_state_file_access_key}}
    secret_access_key: {{s3_aws_cpi_centos_director_state_file_secret_key}}

- name: ubuntu-director-manifest-file
  type: s3
  source:
    bucket:            {{s3_aws_cpi_ubuntu_director_state_file_bucket}}
    versioned_file:    ubuntu-director-manifest.yml
    region_name:       us-east-1
    access_key_id:     {{s3_aws_cpi_ubuntu_director_state_file_access_key}}
    secret_access_key: {{s3_aws_cpi_ubuntu_director_state_file_secret_key}}

- name: centos-director-manifest-file
  type: s3
  source:
    bucket:            {{s3_aws_cpi_centos_director_state_file_bucket}}
    versioned_file:    centos-director-manifest.yml
    region_name:       us-east-1
    access_key_id:     {{s3_aws_cpi_centos_director_state_file_access_key}}
    secret_access_key: {{s3_aws_cpi_centos_director_state_file_secret_key}}

- name: bosh-cpi-release-in
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
    branch: master
    private_key: {{github_deployment_key__bosh-aws-cpi-release}}
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml

- name: bosh-cpi-release-out
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
    branch: master
    private_key: {{github_deployment_key__bosh-aws-cpi-release}}

- name: version-semver
  type: semver
  source:
    key:               current-version # dev-release version
    bucket:            {{s3_aws_cpi_pipeline_bucket}}
    access_key_id:     {{s3_aws_cpi_access_key}}
    secret_access_key: {{s3_aws_cpi_secret_key}}

- name: release-version-semver
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_aws_cpi_pipeline_bucket}}
    access_key_id:     {{s3_aws_cpi_access_key}}
    secret_access_key: {{s3_aws_cpi_secret_key}}

- name: bosh-init
  type: s3
  source:
    regexp: bosh-init-([0-9.]+)-linux-amd64
    bucket: {{s3_bosh_init_bucket}}
    region_name: {{s3_aws_cpi_region}}

- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh.git
    branch: master

- name: bats
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
    branch: master

- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

- name: aws-ubuntu-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: aws-centos-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-centos-7-go_agent
