---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - build-candidate
      - lifecycle
      - promote-candidate

  - name: primary
    jobs:
      - recreate-infrastructure-primary
      - build-candidate
      - lifecycle
      - promote-candidate

  - name: all
    jobs:
      - recreate-infrastructure-primary
      - build-candidate
      - lifecycle
      - promote-candidate

jobs:
  - name: recreate-infrastructure-primary
    serial_groups: [lifecycle]
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: check-for-running-instances
        file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
        params: &recreate-primary-params
          aws_access_key_id:        {{aws_access_key__primary}}
          aws_secret_access_key:    {{aws_secret_key__primary}}
          region_name:              {{aws_region__primary}}
          stack_name:               primary
          stack_prefix:             not-applicable

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        params: *recreate-primary-params

      - task: setup-infrastructure
        file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
        params: *recreate-primary-params

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-src/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: candidate/.*\.tgz}

  - name: lifecycle
    serial_groups: [lifecycle]
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: test
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          aws_access_key_id:            {{aws_access_key__primary}}
          aws_secret_access_key:        {{aws_secret_key__primary}}
          region_name:                  {{aws_region__primary}}
          stack_name:                   primary

  - name: promote-candidate
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts, passed: [lifecycle]}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-out}
        - {trigger: false, get: release-version-semver, params: {bump: major}}

      - task: promote
        file: bosh-cpi-src/ci/tasks/promote-candidate.yml
        params:
          aws_access_key_id: {{aws_access_key__primary}}
          aws_secret_access_key: {{aws_secret_key__primary}}

      - put: bosh-cpi-src-out
        params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

      - put: release-version-semver
        params: {file: release-version-semver/number}

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-src-in
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-cpi-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}

  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}
