---
jobs:
  - name: recreate-infrastructure-us
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}

      - aggregate:
        - do:
          - task: check-for-ubuntu
            file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
            config: &ubuntu-us-config
              params:
                aws_access_key_id:        {{aws_access_key__e2e_us}}
                aws_secret_access_key:    {{aws_secret_key__e2e_us}}
                region_name:              {{aws_region__e2e_us}}
                stack_name:               end2end-ubuntu
                stack_template:           end2end
                stack_prefix:             End2End

          - task: teardown-ubuntu
            file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
            config: *ubuntu-us-config

          - task: setup-ubuntu
            file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
            config: *ubuntu-us-config
        - do:
          - task: check-for-centos
            file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
            config: &centos-us-config
              params:
                aws_access_key_id:        {{aws_access_key__e2e_us}}
                aws_secret_access_key:    {{aws_secret_key__e2e_us}}
                region_name:              {{aws_region__e2e_us}}
                stack_name:               end2end-centos
                stack_template:           end2end
                stack_prefix:             End2End

          - task: teardown-centos
            file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
            config: *centos-us-config

          - task: setup-centos
            file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
            config: *centos-us-config

  - name: recreate-infrastructure-china
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}

      - aggregate:
        - do:
          - task: check-for-ubuntu
            file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
            config: &ubuntu-china-config
              params:
                aws_access_key_id:        {{aws_access_key__e2e_china}}
                aws_secret_access_key:    {{aws_secret_key__e2e_china}}
                region_name:              {{aws_region__e2e_china}}
                stack_name:               end2end-ubuntu
                stack_template:           end2end
                stack_prefix:             End2End

          - task: teardown-ubuntu
            file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
            config: *ubuntu-china-config

          - task: setup-ubuntu
            file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
            config: *ubuntu-china-config
        - do:
          - task: check-for-centos
            file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
            config: &centos-china-config
              params:
                aws_access_key_id:        {{aws_access_key__e2e_china}}
                aws_secret_access_key:    {{aws_secret_key__e2e_china}}
                region_name:              {{aws_region__e2e_china}}
                stack_name:               end2end-centos
                stack_template:           end2end
                stack_prefix:             End2End

          - task: teardown-centos
            file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
            config: *centos-china-config

          - task: setup-centos
            file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
            config: *centos-china-config

  - name: end2end-us-ubuntu
    plan:
      - aggregate:
        - {trigger: true,  get: stemcell,         resource: ubuntu-stemcell }
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params: &setup-director-params
            aws_access_key_id:     {{aws_access_key__e2e_us}}
            aws_secret_access_key: {{aws_secret_key__e2e_us}}
            region_name:           {{aws_region__e2e_us}}
            stack_name:            end2end-ubuntu
            stack_prefix:          End2End
            director_password:     {{bosh_director_password}}
            director_username:     {{bosh_director_username}}
            private_key_data:      {{e2e_private_key}}
            public_key_name:       {{e2e_public_key_name}}
            use_iam:               true
            use_s3_blobstore:      true

      - task: test
        file: bosh-cpi-src/ci/tasks/run-e2e.yml
        config:
          params: &test-params
            aws_access_key_id:          {{aws_access_key__e2e_us}}
            aws_secret_access_key:      {{aws_secret_key__e2e_us}}
            director_password:          {{bosh_director_password}}
            director_username:          {{bosh_director_username}}
            region_name:                {{aws_region__e2e_us}}
            stack_name:                 end2end-ubuntu
            stemcell_name:              bosh-aws-xen-hvm-ubuntu-trusty-go_agent

      - &teardown-director
        task: teardown-director
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: end2end-us-centos
    plan:
      - aggregate:
        - {trigger: true,  get: stemcell,         resource: centos-stemcell }
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            <<: *setup-director-params
            stack_name: end2end-centos

      - task: test
        file: bosh-cpi-src/ci/tasks/run-e2e.yml
        config:
          params:
            <<: *test-params
            stack_name:    end2end-centos
            stemcell_name: bosh-aws-xen-hvm-centos-7-go_agent

      - *teardown-director

  - name: end2end-china-ubuntu
    plan:
      - aggregate:
        - {trigger: true,  get: stemcell,         resource: ubuntu-stemcell}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params: &setup-director-china-params
            aws_access_key_id:     {{aws_access_key__e2e_china}}
            aws_secret_access_key: {{aws_secret_key__e2e_china}}
            director_password:     {{bosh_director_password}}
            director_username:     {{bosh_director_username}}
            private_key_data:      {{e2e_private_key}}
            public_key_name:       {{e2e_public_key_name}}
            region_name:           {{aws_region__e2e_china}}
            stack_name:            end2end-ubuntu
            stack_prefix:          End2End
            use_iam:               true
            use_s3_blobstore:      true

      - task: test
        file: bosh-cpi-src/ci/tasks/run-e2e.yml
        config:
          params: &test-params-china
            aws_access_key_id:          {{aws_access_key__e2e_china}}
            aws_secret_access_key:      {{aws_secret_key__e2e_china}}
            director_password:          {{bosh_director_password}}
            director_username:          {{bosh_director_username}}
            region_name:                {{aws_region__e2e_china}}
            stack_name:                 end2end-ubuntu
            stemcell_name:              bosh-aws-xen-hvm-ubuntu-trusty-go_agent

      - *teardown-director

  - name: end2end-china-centos
    plan:
      - aggregate:
        - {trigger: true,  get: stemcell,         resource: centos-stemcell}
        - {trigger: false, get: bosh-cpi-release, resource: bosh-aws-cpi-release}
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: false, get: bosh-init}
        - {trigger: false, get: bosh-release}

      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            <<: *setup-director-china-params
            stack_name: end2end-centos

      - task: test
        file: bosh-cpi-src/ci/tasks/run-e2e.yml
        config:
          params:
            <<: *test-params-china
            stack_name:    end2end-centos
            stemcell_name: bosh-aws-xen-hvm-centos-7-go_agent

      - *teardown-director

  - name: certify-ubuntu
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: true,  get: bosh-cpi-release, passed: [end2end-us-ubuntu, end2end-china-ubuntu], resource: bosh-aws-cpi-release}
        - {trigger: true,  get: bosh-release,     passed: [end2end-us-ubuntu, end2end-china-ubuntu]}
        - {trigger: true,  get: stemcell,         passed: [end2end-us-ubuntu, end2end-china-ubuntu], resource: ubuntu-stemcell}

      - task: generate-certification
        file: bosh-cpi-src/ci/tasks/generate-certification.yml
        config:
          params:
            bosh_release_name: bosh
            cpi_release_name: bosh-aws-cpi
            stemcell_name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

      - put: certification
        params:
          file: certification-receipt/*.json

  - name: certify-centos
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src}
        - {trigger: true,  get: bosh-cpi-release, passed: [end2end-us-centos, end2end-china-centos], resource: bosh-aws-cpi-release}
        - {trigger: true,  get: bosh-release,     passed: [end2end-us-centos, end2end-china-centos]}
        - {trigger: true,  get: stemcell,         passed: [end2end-us-centos, end2end-china-centos], resource: centos-stemcell}

      - task: generate-certification
        file: bosh-cpi-src/ci/tasks/generate-certification.yml
        config:
          params:
            bosh_release_name: bosh
            cpi_release_name: bosh-aws-cpi
            stemcell_name: bosh-aws-xen-hvm-centos-7-go_agent

      - put: certification
        params:
          file: certification-receipt/*.json

resources:
  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-aws-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: ubuntu-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([0-9.]+)-aws-xen-hvm-ubuntu-trusty-go_agent.tgz
      bucket: bosh-aws-light-stemcells
      region_name: us-east-1

  - name: centos-stemcell
    type: s3
    source:
      regexp: light-bosh-stemcell-([0-9.]+)-aws-xen-hvm-centos-7-go_agent.tgz
      bucket: bosh-aws-light-stemcells
      region_name: us-east-1

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: certification
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: receipt-.*\.json
      region_name: us-east-1
